### PR TITLE
Add Image Header to bootleby

### PR DESCRIPTION
**Pull request by labbott**
We want to be able to add a caboose post build to store some meta information. This requires an image header that lives right after the vector table. The easiest way to add this is with a custom linker script.

### CODE REVIEW

**Review by cbiffle — APPROVED** [review]
This would work -- would it be possible to reduce the header to the first two words, just to keep the size and flash information content down?

If not, that's ok.

**Review by cbiffle — COMMENTED** [review]
Oh hey -- consider copying our memory.x custom linker script fragment into the target dir, appending your symbols, and emitting a link-search line to point to it. That way we don't have to copy-paste the upstream link.x.

**Comment by labbott** [comment]
> Oh hey -- consider copying our memory.x custom linker script fragment into the target dir, appending your symbols, and emitting a link-search line to point to it. That way we don't have to copy-paste the upstream link.x.

I did try something like that at first. The issue is that we can't include the `.header` after the vector table using `INSERT {before, after}` directives because of how `_stext` is defined (https://github.com/rust-embedded/cortex-m/blob/master/cortex-m-rt/link.x.in#L69-L109) . Any other idea I had would have still involved linker script changes.

**Comment by labbott** [comment]
> This would work -- would it be possible to reduce the header to the first two words, just to keep the size and flash information content down?
> 
> If not, that's ok.

Our external tools for caboose reading only rely on the magic + length. Hubris technically uses the full `ImageHeader` structure and can extract the current version/epoch fields. Those fields have only ever been zero and I strongly suspect that information is going to end up in the caboose instead. I'm okay with limiting it to the first two words with the assumption we don't care about any of the other fields.

**Pull request merged**
